[package]
name = "deskpi-fan-pwm"
version = "1.0.0"
edition = "2018"
authors = ["Léon ROUX <Nurrl@users.noreply.github.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
systemstat = "0.1.8"
